language: objective-c
osx_image: xcode7.3
before_install:
    - brew update
    - brew tap homebrew/versions
install:
    - brew install python3
    - easy_install pip
    - brew install ninja
    - brew install gcc49
    - brew install homebrew/dupes/gpatch
    - brew install quilt
    - brew install svn
    - pip install -U pyobjc
script:
    - python3 build.py

